f = open('37.star' ,'w')
f.write('\ndata_\n')
f.write('loop_\n')
f.write('_rlnImageName #1\n')
f.write('_rlnLabel #2 \n')
f.write('_rlnAngleRot #3\n')
f.write('_rlnAngleTilt #4\n')
f.write('_rlnAnglePsi #5 \n')
f.write('_rlnVoltage #6 \n')
f.write('_rlnMagnification #7\n')
f.write('_rlnDetectorPixelSize #8\n')
f.write('_rlnDefocusU #9\n')
f.write('_rlnDefocusV #10\n')
f.write('_rlnDefocusAngle #11 \n')
f.write('_rlnSphericalAberration #12 \n')
f.write('_rlnAmplitudeContrast #13 \n')
f.write('_rlnGroupNumber #14\n')
f.write('_rlnOriginX #15\n')
f.write('_rlnOriginY #16\n')
f.write('_rlnClassNumber #17\n')
f.write('_rlnNormCorrection #18\n')
f.write('_rlnRandomSubset #19\n')
f.write('_rlnLogLikeliContribution #20\n')
f.write('_rlnMaxValueProbDistribution #21\n')
f.write('_rlnNrOfSignificantSamples #22\n')
f.close()
f = open('374.star' ,'w')
f.write('\ndata_\n')
f.write('loop_\n')
f.write('_rlnImageName #1\n')
f.write('_rlnLabel #2 \n')
f.write('_rlnAngleRot #3\n')
f.write('_rlnAngleTilt #4\n')
f.write('_rlnAnglePsi #5 \n')
f.write('_rlnVoltage #6 \n')
f.write('_rlnMagnification #7\n')
f.write('_rlnDetectorPixelSize #8\n')
f.write('_rlnDefocusU #9\n')
f.write('_rlnDefocusV #10\n')
f.write('_rlnDefocusAngle #11 \n')
f.write('_rlnSphericalAberration #12 \n')
f.write('_rlnAmplitudeContrast #13 \n')
f.write('_rlnGroupNumber #14\n')
f.write('_rlnOriginX #15\n')
f.write('_rlnOriginY #16\n')
f.write('_rlnClassNumber #17\n')
f.write('_rlnNormCorrection #18\n')
f.write('_rlnRandomSubset #19\n')
f.write('_rlnLogLikeliContribution #20\n')
f.write('_rlnMaxValueProbDistribution #21\n')
f.write('_rlnNrOfSignificantSamples #22\n')
f.close()
f = open('4.star' ,'w')
f.write('\ndata_\n')
f.write('loop_\n')
f.write('_rlnImageName #1\n')
f.write('_rlnLabel #2 \n')
f.write('_rlnAngleRot #3\n')
f.write('_rlnAngleTilt #4\n')
f.write('_rlnAnglePsi #5 \n')
f.write('_rlnVoltage #6 \n')
f.write('_rlnMagnification #7\n')
f.write('_rlnDetectorPixelSize #8\n')
f.write('_rlnDefocusU #9\n')
f.write('_rlnDefocusV #10\n')
f.write('_rlnDefocusAngle #11 \n')
f.write('_rlnSphericalAberration #12 \n')
f.write('_rlnAmplitudeContrast #13 \n')
f.write('_rlnGroupNumber #14\n')
f.write('_rlnOriginX #15\n')
f.write('_rlnOriginY #16\n')
f.write('_rlnClassNumber #17\n')
f.write('_rlnNormCorrection #18\n')
f.write('_rlnRandomSubset #19\n')
f.write('_rlnLogLikeliContribution #20\n')
f.write('_rlnMaxValueProbDistribution #21\n')
f.write('_rlnNrOfSignificantSamples #22\n')
f.close()
sep = ' '

f = open('run_it018_data.star', 'r')
lines = f.readlines()
for line in lines:
    column = line.split()
    if '@' in line:
        if int(column[1]) == 4:
            f = open('4.star', 'a')
            column.append("\n")
            f.write(sep.join(column))
            f.close()

        if int(column[1]) == 37:
            f = open('37.star', 'a')
            column.append("\n")
            f.write(sep.join(column))
            f.close()

        if int(column[1]) == 374:
            f = open('374.star', 'a')
            column.append("\n")
            f.write(sep.join(column))
            f.close()